name: Prod CI

on:
  push:
    branches:
      - main # 메인 브렌치에 브랜치 머지 시 자동으로 실행

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests with coverage
        run: ./gradlew test jacocoTestReport # 단위 테스트 

      - name: Check coverage
        uses: madrapps/jacoco-report@v1.7.2
        with:
          paths: |
            ${{ github.workspace }}/**/build/reports/jacoco/test/html/index.html
            ${{ github.workspace }}/**/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 80
          min-coverage-changed-files: 80
          title: JaCoCo Coverage Report
          update-comment: true
    
      - name: Show build number
        run: |
          echo "Build Number: ${{ github.run_number }}"
      - name: Show pull request number
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "PR Number: ${{ github.event.pull_request.number }}"
      - name: Get PR Number for Main Branch Merge
        id: get_pr_number
        if: github.ref == 'refs/heads/main'
        run: |
          PR_NUMBER=$(gh pr list --repo ${{ github.repository }} --state closed --json number,mergeCommit --jq ".[] | select(.mergeCommit.oid == \"${{ github.sha }}\") | .number")
          echo "PR_NUMBER=${PR_NUMBER}"
          echo "PR_NUMBER"="${PR_NUMBER}" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set Docker Image Tag
        id: set_docker_image_tag
        env:
          PR_NUMBER: ${{ steps.get_pr_number.outputs.PR_NUMBER }}
        run: |
          DOCKER_IMAGE_TAG="1.1.$PR_NUMBER"
          echo "Docker Image Tag: $DOCKER_IMAGE_TAG"
          echo "DOCKER_IMAGE_TAG"="${DOCKER_IMAGE_TAG}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        env:
          DOCKER_IMAGE_TAG: ${{ steps.set_docker_image_tag.outputs.DOCKER_IMAGE_TAG }}
        run: |
          docker buildx create --use
          docker buildx build \
            --platform linux/amd64 \
            --push \
            -t ${{ secrets.DOCKER_HUB_USERNAME }}/techeerism-spring:$DOCKER_IMAGE_TAG .

      - name: Send Image and Version to Slack
        if: github.ref == 'refs/heads/main' # main 브랜치에 머지 시에만 실행
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/techeerism-spring
          DOCKER_IMAGE_TAG: ${{ steps.set_docker_image_tag.outputs.DOCKER_IMAGE_TAG }}
          SLACK_SECRET: ${{ secrets.SLACK_DEPLOY_SECRET }}
        run: |
          commit_link="https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/commit/${{ github.sha }}"
          curl -X POST https://techeer-029051b54345.herokuapp.com/api/v1/deploy/image \
          -H "Content-Type: application/json" \
          -d '{
                "imageName": "'"$IMAGE_NAME"'",
                "imageTag": "'"$DOCKER_IMAGE_TAG"'",
                "commitLink": "'"$commit_link"'",
                "environment": "production",
                "secret": "'"$SLACK_SECRET"'"
              }'